version: '3'
services:
    spigot-server:
        image: nimmis/spigot
        ports:
            - "25565:25565"
        volumes:
            - ./data:/minecraft
        stdin_open: true
        environment: 
            "EULA": "true"
            "SPIGOT_VER": "1.14.4"
            "MC_MAXMEM": "4g"