name: Skyblock
version: @version@
main: tech.wakame.skyblock.SkyBlock
api-version: 1.13
author: wakame-tech
commands:
  islands:
    description: list islands
  island:
    description: register island <name>
  palette:
    description: edit command palette
  catalog:
    description: open catalog
  genskill:
    description: generate all skills