name: Skyblock
version: @version@
main: tech.wakame.skyblock.SkyBlock
api-version: 1.13
commands:
  islands:
    description: list islands
  island:
    description: register island <name>
  palette:
    description: edit command palette